[package]
name = "account-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0.95"
cxx-qt = "0.7"
cxx-qt-lib = { version="0.7", features = ["qt_full"] }

[build-dependencies]
cxx-qt-build = { version = "0.7" }
